name: LonelyWilderness
main: com.ne0nx3r0.lonely.LonelyWilderness
version: '1.6b'
database: false
description: Lonely /wild command
commands:
    wild:
      description: Lonely wild command
permissions:
  lonely.commands.wild:
    description: Can use /wild
    default: false